### ISSUE TITLE
Signup Process/Feedback

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/tahoe-gui#3]
When using the signup process, I found myself wanting more feedback beyond the (ephemeral) messages in the progress-bar. I also think a separate label for the "invitation code" text-field is a good idea (on my windowmanager, as soon as I focus the window, that text-field is focused and so I can't read the "invitation code" placeholder text in the field, ever).

This might be overkill, but I was thinking perhaps something like this:

 - once you type in the invite code, you get a list of steps
 - the current one is highlighted (possibly with its own spinner/progress-bar)
 - when that step is done, it turns grey (with the final status message)

Part of my thinking here is that we're going to want more information in the wormhole, for example to install tahoe-lafs. We probably want to send a URI indicating where to fetch "a release" from (and this would probably be a wheel file? so there might be several such URIs, one for each platform) along with SHA256-sums of the expected hash for these.

So one "step" will be "download the release", which could take a while depending on connection. Another step will then be "verify release" (i.e. `sha256sum` what we downloaded and compare to the secure hash we received). Maybe (instead) we put an "expected public key" in the JSON, and we download a signature which we verify against the downloaded release, and if that works we check if we found the expected public-key.

The "list of steps" could include a wormhole-JSON-provided blurb/message and even a logo (e.g. the JSON could have a URI where to download the logo, or just inline `uuencoded` data or whatever) -- so then after you've gotten the JSON you switch to the "branded list of steps" thing and the user can see a fine-grained list of what's happening (and what's to come, so they have some idea how long the process might take).

Then, also, if a step fails it could have a "more info" or similar button where we can dump some logs or whatever else might help us help the user figure out what failed.

**Comment by crwood** [comment]
Thanks for the feedback! :)

> When using the signup process, I found myself wanting more feedback beyond the (ephemeral) messages in the progress-bar.

What sort of additional feedback, specifically, would you like to see here (or are you referring solely to the feedback pertaining to downloading a Tahoe-LAFS release and verifying the checksum/signature as described later in your post)?

>I also think a separate label for the "invitation code" text-field is a good idea (on my windowmanager, as soon as I focus the window, that text-field is focused and so I can't read the "invitation code" placeholder text in the field, ever).

Agreed. For what it's worth, there are a few other UI adjustments that also need to be made to this widget (like adjusting the geometry/sizing policy of the input field itself so as to not cut off longer invite codes, providing a confirmation/go button to support mouse-only engagement, handling cancel/close events, etc.). In any case, I've added this specifically to my TODO (and will fix it soon!).

>This might be overkill, but I was thinking perhaps something like this:
>
>   * once you type in the invite code, you get a list of steps
>   * the current one is highlighted (possibly with its own spinner/progress-bar)
>   * when that step is done, it turns grey (with the final status message)
>
> Part of my thinking here is that we're going to want more information in the wormhole, for example to install tahoe-lafs. We probably want to send a URI indicating where to fetch "a release" from (and this would probably be a wheel file? so there might be several such URIs, one for each platform) along with SHA256-sums of the expected hash for these.

I disagree. I'm not convinced that granting _individual storage providers(!)_ the authority to push Tahoe-LAFS releases to clients is something we should (ever) support (if that is indeed what you are proposing here -- and please correct me if it isn't). If it were, then any malicious storage provider could easily pwn their entire userbase by simply putting a URI to a backdoored "release" in their initial wormhole/JSON response. Checksums would do nothing to mitigate this (unless those checksums came from a "trusted" source -- but if that's the case, why not fetch the release _from_ that "trusted" source in the first place?). In short, this design jeopardizes the promise of "provider-independent security" and makes the POLA Bears angry. :)

That being said, I would advocate instead that any and all "software install/update"-type functionality be separated completely from the "accept an invite"/wormhole-type functionality both a) in terms of the source of delivery (since, generally speaking, software installs/updates should arguably come from their creators and/or other sufficiently "trusted" sources -- like, say, your OS/distro's package repository) and b) in terms of the availability of such functionality within the GUI application itself (since the action of checking for software updates is something that should occur on a different schedule than the user-determined action of accepting an invite). Accordingly, I see no good reason or use-case for why we should couple these two things together (but am always open to the fact that I might be mistaken!).

Beyond this, I have some additional reservations regarding the suggestion of providing Tahoe-LAFS updates in the form of python wheels (particularly on Windows and macOS systems where, in light of the goal of providing good and familiar UX, we presently provide both Tahoe-GUI and Tahoe-LAFS as self-contained binary packages that do not depend on the availability of a general-purpose python interpreter) but I'll direct those concerns to Issue #4 later on where that conversation should probably be happening instead.

>The "list of steps" could include a wormhole-JSON-provided blurb/message and even a logo (e.g. the JSON could have a URI where to download the logo, or just inline uuencoded data or whatever) -- so then after you've gotten the JSON you switch to the "branded list of steps" thing and the user can see a fine-grained list of what's happening (and what's to come, so they have some idea how long the process might take).

Yes.. I've mentioned doing something like this a couple of times (along with adding a URI to a NEWS file that clients could poll, e.g., to be informed of pending grid downtime and other announcements) but I believe the consensus at the time was to push branding-related stuff back until after the initial MVP release/testing phase (and I know @liz315 had some UX-related objections against the NEWS file idea). Maybe we should revisit this discussion again at the next GUI meeting? Adding a service name and logo/icon, at least, wouldn't be terribly difficult to do (though, at the same time, I wouldn't want to fall into the trap of further dragging out a release in the name of adding additional features).

>Then, also, if a step fails it could have a "more info" or similar button where we can dump some logs or whatever else might help us help the user figure out what failed.

Good call. I can dump tracebacks/logs into error dialogs' [`detailedText`](https://doc.qt.io/qt-5/qmessagebox.html#detailedText-prop) property (which could/should also probably contain further instructions about how/where to get help..). Adding this to my TODO -- along with the prerequisite of actually implementing meaningful logs. Thanks again! :)

**Comment by meejah** [comment]
> I disagree. I'm not convinced that granting individual storage providers(!) the authority to push Tahoe-LAFS releases to clients is something we should (ever) support (if that is indeed what you are proposing here -- and please correct me if it isn't). If it were, then any malicious storage provider could easily pwn their entire userbase by simply putting a URI to a backdoored "release" in their initial wormhole/JSON response.

How are users going to install Tahoe-LAFS then?

In any case, you're already trusting the provider to give you software -- after all, you downloaded the GUI, right? I don't really see how having one more thing you trust them for (i.e. give them the most up-to-date release of Tahoe) is any more authority.

**Comment by meejah** [comment]
> Beyond this, I have some additional reservations regarding the suggestion of providing Tahoe-LAFS updates in the form of python wheels [..]

Okay, yes, I guess I meant that as illustration ;) (And the blurb/logo thing yes I was referencing previous conversations on this -- just trying to show where it could fit in).

**Comment by meejah** [comment]
Just to clarify the "provider" stuff, too: there's multiple types of providers -- there's providing an individual storage node (in, e.g., the "one true grid" or in a "friend-net" type grid) and then there's "entire grid providers" (which is the kind I mean for the above release-installing feature).

...but, yes, I take your point that getting the actual software from "grid providers" isn't a good idea. But, there's also not a general way to securely distribute software period. So. Hmm. Yes, sad POLA bear.

If we're asking users to install Tahoe-LAFS on their own first, then the GUI needs a way to select *which* tahoe-lafs you'd like to use...

**Comment by meejah** [comment]
...and then I guess we're just "Really Hoping" that a provider a) points users to our website, instead of e.g. their own and b) that users will actually check the signatures?

That is, if someone is a Grid Provider, they're very likely going to have some kind of "sign up" page with a link like "please install this Tahoe LAFS software!" -- so they could then presumably just put the "malicious Tahoe LAFS" software on that page.

**Comment by meejah** [comment]
I guess the better solution would be to burn in URIs/methods to download tahoe for people in "the most-secure way" we can think of. For example, getting the latest release from PyPI on Linux, *and* downloading + checking the signature (do we sign these now?). We could then pin public-keys in the tahoe-gui release, too.

**Ideally** I guess we'd deploy TUF ("the update framework") but that seems more like the OS's job ;)

**Comment by meejah** [comment]
The answer to "do we sign PyPI releases?" is "yes".

**Comment by crwood** [comment]
>How are users going to install Tahoe-LAFS then?

Currently, they don't need to (at least not on macOS or Windows); a working (1.12a) `tahoe`/`tahoe.exe` is _already_ included inside of the [Tahoe-GUI.dmg](https://buildbot.gridsync.io/packages/Tahoe-GUI.dmg) (macOS) and [Tahoe-GUI-win64.zip](https://buildbot.gridsync.io/packages/Tahoe-GUI-win64.zip) (Windows) bundles. Unzip [this file](https://buildbot.gridsync.io/packages/Tahoe-GUI-win64.zip) and have a peek inside the included "Tahoe-LAFS" subdirectory and you'll see what I mean. :)

These binaries are built using [PyInstaller](http://www.pyinstaller.org/) and thus do not even require a general-purpose python interpreter to be installed on the host system (which is an _enormous_ plus from a UX perspective -- we no longer have to tell users to go download python2 _and_ python3 _and_ then our GUI). All that users need to do (right now) is download/install the package, double click the included `Tahoe-GUI.app`/`Tahoe-GUI.exe`, and enter their invite code when the window pops up. It doesn't get any simpler than that. Under the hood, the GUI process appends the bundled "Tahoe-LAFS" subdirectory to the environment $PATH (if it detects that you're using the frozen/binary distribution) and uses the `tahoe`/`tahoe.exe` contained therein (unless it finds another `tahoe`/`tahoe.exe` on the $PATH, in which case it will use that one instead).

Obviously, we still need to harden that build-process, sign packages, upload to a host that isn't my cheap VPS, etc. but we we'll be doing this sort of stuff anyway for the GUI (and hopefully soon!)

As of right now, GNU/Linux users will need to install Tahoe-LAFS manually using either `pip` or their distro's package-manager (both of which are arguably more "trusted" than a random storage provider and which we should probably be encouraging the use of anyway) since we currently do not provide GUI packages for Debian, Redhat, etc. When we _do_ provide such packages (which @david415 volunteered to help with a while back -- at least for debian :) ) we need only specify 'tahoe-lafs' (>=1.12) as a package dependency.

>In any case, you're already trusting the provider to give you software -- after all, you downloaded the GUI, right? I don't really see how having one more thing you trust them for (i.e. give them the most up-to-date release of Tahoe) is any more authority.

Are we? I was under the impression that users would be downloading the GUI from LeastAuthority.com (and/or their distro's repo/PyPI) and _not_ the storage provider (and that the storage provider would insert their "branding" into the client via the initial wormhole/invite since that's easier for them).. Am I wrong?

If not, then I would argue the design you've described increases the attack-surface (and to no discernible advantage) since the user would have to trust a) LeastAuthority.com (for the GUI) b) Tahoe-LAFS.org and/or PyPI/debian/etc. (for Tahoe-LAFS), _and_ c) Potentially-Malicious-Storage-Provider.biz (to provide "the most up-to-date release of Tahoe"). With the current design (or the one I had in mind), users need only trust the first two.

On that note, I should probably ask more broadly: why _should_ a third party be trusted to provide "the most up-to-date release of Tahoe" _instead of_ Tahoe-LAFS.org or LeastAuthority.com (who will always need to be trusted anyway and who are arguably better suited at the task of actually cutting releases)? And why would a third party storage-provider _want_ the extra burden of having to maintain their own distribution of Tahoe-LAFS for their users (given, again, that any additional "branding" could be provided via the invite/wormhole/setup flow)? What if that storage provider (out of laziness and not malice) fails to keep their Tahoe-LAFS distribution up-to-date in the event of a serious security vulnerability? And what happens if a user wants to join two or more storage grids using their GUI, each of which provides their own diverging Tahoe-LAFS distributions?

More generally: what advantages do users or storage providers actually gain with this design (of getting software updates from storage providers and not us)? I can think of plenty of (potential) harms, but am not seeing any (actual) benefits yet (and don't count saving bandwidth costs as a benefit).

**Comment by crwood** [comment]
>Just to clarify the "provider" stuff, too: there's multiple types of providers -- there's providing an individual storage node (in, e.g., the "one true grid" or in a "friend-net" type grid) and then there's "entire grid providers" (which is the kind I mean for the above release-installing feature).

>...but, yes, I take your point that getting the actual software from "grid providers" isn't a good idea. But, there's also not a general way to securely distribute software period. So. Hmm. Yes, sad POLA bear.

Ah! I started responding to your first reply _before_ I saw all these other ones. I guess I should have refreshed the page before hitting that "Comment" button. :)

Anyways, we seem to be in agreement! (And I, too, was thinking of "providers" in terms of "entire grid providers" -- e.g., Least Authority).

**Comment by crwood** [comment]
>If we're asking users to install Tahoe-LAFS on their own first, then the GUI needs a way to select which tahoe-lafs you'd like to use...

As mentioned above, currently, Tahoe-GUI will use the first `tahoe`/`tahoe.exe` it finds in $PATH (thus it already uses whatever installation the user would normally prefer to use from the command-line). If macOS/Windows users download the .dmg/.zip bundle from us, however, a (currently 1.12a) Tahoe-LAFS distribution will be available (and thus we don't have to worry about that whole extra download-the-latest-tahoe-lafs-version step -- nor the additional trust-related issues described above). I _will_, however, have to add some additional code to do a version-check on any/all installed versions and make sure that, at minimum, the GUI selects a magic-folder-supporting (1.12a+) release (in the event that, e.g., it finds a lower version of Tahoe-LAFS earlier in the $PATH..).

Do you think that we need to provide to users a way of _manually_ selecting their Tahoe-LAFS version (beyond the currently-described ordering-preference of selecting whichever `tahoe`/`tahoe.exe` is found first in $PATH _and_ which meets the criteria of being of version 1.12a+)?


>...and then I guess we're just "Really Hoping" that a provider a) points users to our website, instead of e.g. their own and b) that users will actually check the signatures?

>That is, if someone is a Grid Provider, they're very likely going to have some kind of "sign up" page with a link like "please install this Tahoe LAFS software!" -- so they could then presumably just put the "malicious Tahoe LAFS" software on that page.

Yes.. These are unfortunate considerations that I don't think we'll be able to ever fully mitigate. :(

One of the best things we can do at this stage (beyond actually providing the GUI, hosting the storage grid, _and_ convincing users to check sigs/checksums) would probably be to provide additional incentives to third party storage/grid providers that would encourage them to point their users to our GUI. If branding is the only reason/requirement that a (non-malicious) third party provider has for providing their own client, we can ensure that that's provided through the initial wormhole/setup process we mentioned earlier. If there are other reasons beyond this, we should find out what those reasons are and see what we can do to meet them on our end. Ideally, users should be able to use our GUI with _any_ Tahoe-LAFS grid (and will prefer to use ours because of this goal).

>I guess the better solution would be to burn in URIs/methods to download tahoe for people in "the most-secure way" we can think of. For example, getting the latest release from PyPI on Linux, and downloading + checking the signature (do we sign these now?). We could then pin public-keys in the tahoe-gui release, too.

Yeah.. Something like this. Consider also that once 1.12 lands (and if lands with PR [381](https://github.com/tahoe-lafs/tahoe-lafs/pull/381) merged) we _probably_ won't have a need to upgrade Tahoe-LAFS on a schedule that's any more rapid than the release schedule of Tahoe-GUI itself (which will buy us more time to figure out the best way to do this _and_, in the case of macOS/Windows, allow us to include Tahoe-LAFS' "latest" version in the GUI bundle whenever we cut a new release). We'll still have to figure out a good way to self-update the GUI, however (as I'm guessing that the GUI will see more "releases" over the next 12 months than Tahoe-LAFS proper).

>Ideally I guess we'd deploy TUF ("the update framework") but that seems more like the OS's job ;)

I still need to learn more about TUF. Thanks (again) for the reminder!. :)

**Comment by meejah** [comment]
Okay, so sorry for the long thread! In conclusion:

 - ideally "we" (leastauthority and/or tahoe-lafs.org) are providing tahoe-gui binary packages
 - (that is, grid providers just give out a link)
 - (and we're Really Hoping the user checks the signature!)
 - OS X and Windows users get a bundled Tahoe

Open questions:

 - updating tahoe-lafs GUI itself (and the bundled Tahoe on Windows, OS/X)
 - can we do better than Really Hoping users check sigs? (e.g. is there any new app-store type stuff we can utilize?)

For Linux users, yes it's best if they use their system packages.

If they *don't*, though, I think it's better if tahoe-gui runs "pip install" for them, as pip doesn't check signatures and only checks hashes with a lot of coaxing. So I think it'd be a bit of a win for us to download the dist + signature and install it in a virtualenv for them (if "which tahoe" fails, basically). And/or at least offer to do this.

**Comment by crwood** [comment]
No need to apologize! It's great to be able to figure this stuff out sooner rather than later. :)

Thanks for the summary -- that all sounds about right to me. I'll look into TUF as soon as I manage to find some free time and try to narrow down our options a little more..

re. app-store stuff, we can (and should) get an Apple Developer signing key at some point (which will at least remove the "untrusted developer" warning). I believe Apple's App Store forbids GPL'd code, however (but I'll look into this too). :(

I'm not sure about Windows..

**Comment by crwood** [comment]
Also, if we _really_ wanted to, we could provide binaries for Linux (in the same way that they're currently provided on macOS and Windows) -- but even just _typing_ that out feels wrong to me..

**Comment by meejah** [comment]
Well, next step (i.e. after deciding "distros aren't up-to-date enough") for at least Debian-ish linuxes would probably be to provide our own `.deb` repository-in-the-cloud ("ppa" for Ubuntu) like `deb.leastauthority.com` or similar.
